server:
  port: 8001

spring:
  application:
    name: itest-consumer-8001
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.44.179:8848/
  #redis
  redis:
    host: 124.70.44.179
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        max-active: 8

#server-url:
#  service-login: http://itest-provider-9001

feign:
  sentinel:
    enabled: true